# Generated by Django 3.2.8 on 2021-11-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_key', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
